### ISSUE TITLE
A coupon for 100$ for digitalocean

### ISSUE THREAD

**Issue by grzegorzkoziolek** [SlavaUkraineSince1991/DDoS-for-all#1]
Maybe it's worth adding to the description:
https://www.digitalocean.com/try/free-trial-offer?utm_campaign=emea_brand_kw_en_cpc&utm_adgroup=digitalocean_credit_exact&_keyword=digitalocean%20promo%20code&_device=c&_adposition=&utm_content=conversion&utm_medium=cpc&utm_source=google&gclid=CjwKCAjw_tWRBhAwEiwALxFPoVDd0Hf4gWRu_LpvHetaMH-ngZMQDnBquNqMCuo-CRWFkGztRCiFLBoCyykQAvD_BwE

**Comment by grzegorzkoziolek** [comment]
You need to deposit 5$ and you get 100$ for 60 days

**Comment by SlavaUkraineSince1991** [comment]
OK, thanks, I'll add it)
