### ISSUE TITLE
Сумісніть образом різних платформ

### ISSUE THREAD

**Issue by Rommgo** [SlavaUkraineSince1991/DDoS-for-all#2]
Реалізувати підтримку образа різними платформами, в багатьох є пристрої відмінні від звичайних пк, але на які можна встановити докер і запустити образ, в ідеалі звичайно щоб він міг запуститись і на чайнику з wi-fi... 

Особисто маю одноплатний пк расбері 4(платформа linux/arm/v7 ), але на ній цей образ не запускається, інші одноплатні пк можуть мати платформу linux/arm64/v8. 

В мене є можливість самому це зробити, але не маю на то достатньо часу, по можливості буду пробувати.

Можливо ця лінка буде в нагоді 
https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/

**Comment by iamtodor** [comment]
@Rommgo на арм есть вот такая репка https://github.com/Arriven/db1000n и дока к ней https://arriven.github.io/db1000n/#use-vpn-if-you-are-in-ukraine
тоже конфиг динамический

**Comment by Rommgo** [comment]
@iamtodor писали що db1000n вже не працює, хз, то можна спробувати. 
В доці під Linux 32bit, битий лінк, тре пробувати, дякую за наводку
Хотілось би цю репу допиляти

**Comment by iamtodor** [comment]
@Rommgo а где писали, что db1000n не работает? не видел такого, все успешно работает)

**Comment by SlavaUkraineSince1991** [comment]
А із чим саме проблеми? Із встановленням Докера?

**Comment by Rommgo** [comment]
@SlavaUkraineSince1991 
Пробелма не в докері, ось що пише : 
WARNING: The requested image`s platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and specific platform was requested standart_init_linux.go:228: exec user process caused: exec fomat error
