### ISSUE TITLE
альтернатива віртуальній машині

### ISSUE THREAD

**Issue by ffred1962** [SlavaUkraineSince1991/DDoS-for-all#3]
Доброго дня!
Як альтернативу віртуальній машині у хмарі можна спробувати запустити докери у пісочниці
https://labs.play-with-docker.com/
Тут можна запустити кілька віртуалок (здається - 4). 
Ресурс безкоштовний, але потрібна звичайна реєстрація
Тривалість сессії обмежена - близько 4 годин

**Comment by SlavaUkraineSince1991** [comment]
Супер, дякую, візьмемо до уваги)
